export const links = [
	{
		tag: 'Intellectual',
		title: 'Fixing Nigeria Election: Chief Mike Agbedor Abu Ozekhome,',
		date: 'May 24, 2020',
		description:
			'Lorem ipsum dolor sit amet consectetur. Nullam auctor sit rhoncus id eu ipsum. Euismod pretium donec duis mattis ultricies fermentum. A nisl cras pellentesque tristique mauris arcu ornare sit facilisis. Ullamcorper elementum massa elit dolor morbi mauris. Ut imperdiet risus mauris ultricies eget. Dictum nunc quis neque id mattis. Non sit iaculis nec mauris et ac fames a et. Maecenas sit ornare scelerisque ultrices pellentesque sed. Blandit neque erat rhoncus lobortis donec in tortor. Sed interdum nunc sit nunc tellus egestas. Morbi dolor nisl odio eros vitae. Nibh purus faucibus nunc at. Eleifend sodales sit turpis ridiculus. Euismod lobortis iaculis platea bibendum luctus dolor. Enim sed urna phasellus cursus et lacus nunc nec quisque. Sed tincidunt turpis sit suspendisse quam quis. Nec nibh vel tempor diam magna. Non arcu arcu enim sed euismod imperdiet mattis sed consectetur. Pellentesque ac urna sed diam. Massa lacus facilisis imperdiet scelerisque. Ac egestas condimentum sem non vitae scelerisque elit. Lectus consequat scelerisque tristique tortor neque nulla enim odio aliquam. Quam sem facilisi nisl integer consequat in scelerisque amet. Vulputate sapien vulputate pharetra cursus dignissim ridiculus. Tortor a a non porta ipsum erat gravida etiam. Dui phasellus lacinia accumsan ornare fusce mattis. Aliquet volutpat sed ornare neque gravida nec lorem. Id dignissim netus egestas nec vitae. sem non vitae scelerisque elit. Lectus consequat scelerisque tristique tortor neque nulla enim odio aliquam. Quam sem facilisi nisl integer consequat in scelerisque amet. Vulputate sapien vulputate pharetra cursus dignissim ridiculus. Tortor a a non porta ipsum. Lorem ipsum dolor sit amet consectetur. Nullam auctor sit rhoncus id eu ipsum. Euismod pretium donec duis mattis ultricies fermentum. A nisl cras pellentesque tristique mauris arcu ornare sit facilisis. Ullamcorper elementum massa elit dolor morbi mauris. Ut imperdiet risus mauris ultricies eget. Dictum nunc quis neque id mattis. Non sit iaculis nec mauris et ac fames a et. Maecenas sit ornare scelerisque ultrices pellentesque sed. Blandit neque erat rhoncus lobortis donec in tortor. Sed interdum nunc sit nunc tellus egestas. Morbi dolor nisl odio eros vitae. Nibh purus faucibus nunc at. Eleifend sodales sit turpis ridiculus. Euismod lobortis iaculis platea bibendum luctus dolor. Enim sed urna phasellus cursus et lacus nunc nec quisque. Sed tincidunt turpis sit suspendisse quam quis. Nec nibh vel tempor diam magna. Non arcu arcu enim sed euismod imperdiet mattis sed consectetur. Pellentesque ac urna sed diam. Massa lacus facilisis imperdiet scelerisque. Ac egestas condimentum sem non vitae scelerisque elit. Lectus consequat scelerisque tristique tortor neque nulla enim odio aliquam. Quam sem facilisi nisl integer consequat in scelerisque amet. Vulputate sapien vulputate pharetra cursus dignissim ridiculus. ',
		info: '238 Reads - 3 Mins Reading',
		slug: 'FixingNigeria',
	},
	{
		tag: 'Political',
		title: 'Intellectual Property Law In Nigeria',
		date: 'May 24, 2020',
		description:
			'Lorem ipsum dolor sit amet consectetur. Nullam auctor sit rhoncus id eu ipsum. Euismod pretium donec duis mattis ultricies fermentum. A nisl cras pellentesque tristique mauris arcu ornare sit facilisis. Ullamcorper elementum massa elit dolor morbi mauris. Ut imperdiet risus mauris ultricies eget. Dictum nunc quis neque id mattis. Non sit iaculis nec mauris et ac fames a et. Maecenas sit ornare scelerisque ultrices pellentesque sed. Blandit neque erat rhoncus lobortis donec in tortor. Sed interdum nunc sit nunc tellus egestas. Morbi dolor nisl odio eros vitae. Nibh purus faucibus nunc at. Eleifend sodales sit turpis ridiculus. Euismod lobortis iaculis platea bibendum luctus dolor. Enim sed urna phasellus cursus et lacus nunc nec quisque. Sed tincidunt turpis sit suspendisse quam quis. Nec nibh vel tempor diam magna. Non arcu arcu enim sed euismod imperdiet mattis sed consectetur. Pellentesque ac urna sed diam. Massa lacus facilisis imperdiet scelerisque. Ac egestas condimentum sem non vitae scelerisque elit. Lectus consequat scelerisque tristique tortor neque nulla enim odio aliquam. Quam sem facilisi nisl integer consequat in scelerisque amet. Vulputate sapien vulputate pharetra cursus dignissim ridiculus. Tortor a a non porta ipsum erat gravida etiam. Dui phasellus lacinia accumsan ornare fusce mattis. Aliquet volutpat sed ornare neque gravida nec lorem. Id dignissim netus egestas nec vitae. sem non vitae scelerisque elit. Lectus consequat scelerisque tristique tortor neque nulla enim odio aliquam. Quam sem facilisi nisl integer consequat in scelerisque amet. Vulputate sapien vulputate pharetra cursus dignissim ridiculus. Tortor a a non porta ipsum. Lorem ipsum dolor sit amet consectetur. Nullam auctor sit rhoncus id eu ipsum. Euismod pretium donec duis mattis ultricies fermentum. A nisl cras pellentesque tristique mauris arcu ornare sit facilisis. Ullamcorper elementum massa elit dolor morbi mauris. Ut imperdiet risus mauris ultricies eget. Dictum nunc quis neque id mattis. Non sit iaculis nec mauris et ac fames a et. Maecenas sit ornare scelerisque ultrices pellentesque sed. Blandit neque erat rhoncus lobortis donec in tortor. Sed interdum nunc sit nunc tellus egestas. Morbi dolor nisl odio eros vitae. Nibh purus faucibus nunc at. Eleifend sodales sit turpis ridiculus. Euismod lobortis iaculis platea bibendum luctus dolor. Enim sed urna phasellus cursus et lacus nunc nec quisque. Sed tincidunt turpis sit suspendisse quam quis. Nec nibh vel tempor diam magna. Non arcu arcu enim sed euismod imperdiet mattis sed consectetur. Pellentesque ac urna sed diam. Massa lacus facilisis imperdiet scelerisque. Ac egestas condimentum sem non vitae scelerisque elit. Lectus consequat scelerisque tristique tortor neque nulla enim odio aliquam. Quam sem facilisi nisl integer consequat in scelerisque amet. Vulputate sapien vulputate pharetra cursus dignissim ridiculus. ,',
		info: '238 Reads - 3 Mins Reading',
		slug: 'IntellectualProperty',
	},
	{
		tag: 'Constitution',
		title: 'EFFC-DSS Clash a National Embarrassment',
		date: 'May 24, 2020',
		description:
			'Lorem ipsum dolor sit amet consectetur. Nullam auctor sit rhoncus id eu ipsum. Euismod pretium donec duis mattis ultricies fermentum. A nisl cras pellentesque tristique mauris arcu ornare sit facilisis. Ullamcorper elementum massa elit dolor morbi mauris. Ut imperdiet risus mauris ultricies eget. Dictum nunc quis neque id mattis. Non sit iaculis nec mauris et ac fames a et. Maecenas sit ornare scelerisque ultrices pellentesque sed. Blandit neque erat rhoncus lobortis donec in tortor. Sed interdum nunc sit nunc tellus egestas. Morbi dolor nisl odio eros vitae. Nibh purus faucibus nunc at. Eleifend sodales sit turpis ridiculus. Euismod lobortis iaculis platea bibendum luctus dolor. Enim sed urna phasellus cursus et lacus nunc nec quisque. Sed tincidunt turpis sit suspendisse quam quis. Nec nibh vel tempor diam magna. Non arcu arcu enim sed euismod imperdiet mattis sed consectetur. Pellentesque ac urna sed diam. Massa lacus facilisis imperdiet scelerisque. Ac egestas condimentum sem non vitae scelerisque elit. Lectus consequat scelerisque tristique tortor neque nulla enim odio aliquam. Quam sem facilisi nisl integer consequat in scelerisque amet. Vulputate sapien vulputate pharetra cursus dignissim ridiculus. Tortor a a non porta ipsum erat gravida etiam. Dui phasellus lacinia accumsan ornare fusce mattis. Aliquet volutpat sed ornare neque gravida nec lorem. Id dignissim netus egestas nec vitae. sem non vitae scelerisque elit. Lectus consequat scelerisque tristique tortor neque nulla enim odio aliquam. Quam sem facilisi nisl integer consequat in scelerisque amet. Vulputate sapien vulputate pharetra cursus dignissim ridiculus. Tortor a a non porta ipsum. Lorem ipsum dolor sit amet consectetur. Nullam auctor sit rhoncus id eu ipsum. Euismod pretium donec duis mattis ultricies fermentum. A nisl cras pellentesque tristique mauris arcu ornare sit facilisis. Ullamcorper elementum massa elit dolor morbi mauris. Ut imperdiet risus mauris ultricies eget. Dictum nunc quis neque id mattis. Non sit iaculis nec mauris et ac fames a et. Maecenas sit ornare scelerisque ultrices pellentesque sed. Blandit neque erat rhoncus lobortis donec in tortor. Sed interdum nunc sit nunc tellus egestas. Morbi dolor nisl odio eros vitae. Nibh purus faucibus nunc at. Eleifend sodales sit turpis ridiculus. Euismod lobortis iaculis platea bibendum luctus dolor. Enim sed urna phasellus cursus et lacus nunc nec quisque. Sed tincidunt turpis sit suspendisse quam quis. Nec nibh vel tempor diam magna. Non arcu arcu enim sed euismod imperdiet mattis sed consectetur. Pellentesque ac urna sed diam. Massa lacus facilisis imperdiet scelerisque. Ac egestas condimentum sem non vitae scelerisque elit. Lectus consequat scelerisque tristique tortor neque nulla enim odio aliquam. Quam sem facilisi nisl integer consequat in scelerisque amet. Vulputate sapien vulputate pharetra cursus dignissim ridiculus.',
		info: '238 Reads - 3 Mins Reading',
		slug: 'EFFC-DSS',
	},
];
